name: setup node.js project with dependencies

on:
  workflow_dispatch:
    inputs:
      repoURL:
        description: Repo URL to download
        required: true
      packageManager:
        description: Package manager to be used
        required: true
        default: npm
      artifactName:
        description: artifact name
        required: true
      nodeVersion:
        description: Node.js version
        required: false
        default: 16.x

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Setup node.js
        uses: actions/setup-node@v3.4.1
        with:
          node-version: ${{ github.event.inputs.nodeVersion }}
      
      - name: Clone repository
        run: git clone ${{ github.event.inputs.repoURL }} project

      - name: Install dependencies
        run: cd project && ${{ github.event.inputs.packageManager }} install

      - name: Compress the project
        run: tar -czf ${{ github.event.inputs.artifactName }}.tar.gz project

      - name: upload artifacts
        uses: nanoufo/action-upload-artifacts-and-release-assets@v1.4
        with:
          path: ${{ github.event.inputs.artifactName }}.tar.gz
